### ISSUE TITLE
`401 UNAUTHORIZED`でリダイレクトしない

### ISSUE THREAD

**Issue by Cj-bc** [Sakuten/lottery-frontend#10]
ログイン状態で鯖停止、再起動した際401が返るようにはなったが、トップへのリダイレクトがされず、エラーメッセージがずっと出ている状態です。
本当はトップにリダイレクトして欲しいのでなんとかならないかなぁと

```
frontend_1  | ℹ ｢hot｣: WebSocket Client Connected
backend_1   | 172.18.0.1 - - [16/Jun/2018 23:10:23] "GET /api/status HTTP/1.1" 401 -
backend_1   | 172.18.0.1 - - [16/Jun/2018 23:10:23] "GET /api/classrooms HTTP/1.1" 200 -
backend_1   | 172.18.0.1 - - [16/Jun/2018 23:10:23] "GET /api/lotteries HTTP/1.1" 200 -
backend_1   | 172.18.0.1 - - [16/Jun/2018 23:10:33] "OPTIONS /api/status HTTP/1.1" 200 -
backend_1   | 172.18.0.1 - - [16/Jun/2018 23:10:33] "GET /api/status HTTP/1.1" 401 -
backend_1   | 172.18.0.1 - - [16/Jun/2018 23:10:43] "OPTIONS /api/status HTTP/1.1" 200 -
backend_1   | 172.18.0.1 - - [16/Jun/2018 23:10:43] "GET /api/status HTTP/1.1" 401 -
```
以下、
```
backend_1   | 172.18.0.1 - - [16/Jun/2018 23:10:43] "OPTIONS /api/status HTTP/1.1" 200 -
backend_1   | 172.18.0.1 - - [16/Jun/2018 23:10:43] "GET /api/status HTTP/1.1" 401 -
```
この二行がずっと続いている

**Comment by coord-e** [comment]
Related to #9
修正されていないということですか？

2018/06/17 8:12、Cj-bc <notifications@github.com>のメール:

**Comment by Cj-bc** [comment]
いいえ、前はエラーメッセージ（赤い枠で出るやつ）に`{}`とだけ出ていたのが`{"message": "UNAUTORIZED"}`と出るようにはなりました。しかしそのあとにリダイレクトが行われないということです。

**Comment by Cj-bc** [comment]
<img width="719" alt="2018-06-17 8 58 12" src="https://user-images.githubusercontent.com/16875061/41503353-b0f9b58c-720c-11e8-9413-371ca2ea3e12.png">
参考までに現状を

**Comment by coord-e** [comment]
一応使ってるフロントエンドのcommit hashを送ってください

**Comment by Cj-bc** [comment]
う〜ん、あ、もしかしたらマージされる前のっぽい...
ちょっと待って確認しますorz

**Comment by Cj-bc** [comment]
ごめんなさいmerge差分落としてないだけでした..
エラーがいつもと変わっていたので更新されてると思ってしまった...
きちんとリダイレクトされました、大丈夫です.,.
